### ISSUE TITLE
PgComposite not properly escaping parenthesis

### ISSUE THREAD

**Issue by chris-simple** [pomm-project/Foundation#104]
https://github.com/pomm-project/Foundation/blob/96ae9d6ef29359a8fc56b7867ba0bda574447d69/sources/lib/Converter/PgComposite.php#L99

I believe the above regex pattern should include a ")" character. If a text value has a closing parenthesis, but does not contain a comma or space, then the parenthesis will not be escaped. This will cause Postgres will assume the tuple has ended, and it will likely cause a SQL error.

Here is the error I received.
```
[04-Jan-2018 19:23:03 UTC] [emergency] PommProject\Foundation\Exception\SqlException:
SQL error state '22P02' [ERROR]
====
ERROR:  malformed record literal: "(e74212f5-e55d-4e94-a4ff-e8b0c07eb4f4,"",[],<p>this-breaks-it-)</p>,"",f)"
DETAIL:  Too few columns.
```

It works fine when I make the following change to line 99
```
} elseif (preg_match('/[,)\s]/', $val)) {
```

**Comment by chanmix51** [comment]
Can you please provide a test sample of the data you had a problem with? 

    SELECT '("close")'::test_type`

**Comment by chris-simple** [comment]
Thanks for the response.

I'm not totally sure what you're asking for, but here is custom type definition:
```
CREATE TYPE component_content AS (
    content_id UUID,
    content_name TEXT,
    conditions JSON,
    content TEXT,
    help_text TEXT,
    is_default BOOLEAN
);
```
That is used as a column type on a couple of our tables.
And here is a sample tuple which fails to insert with the current code:
```
(e74212f5-e55d-4e94-a4ff-e8b0c07eb4f4,"",[],<p>this-breaks-it-)</p>,"",f)
```

In this example it is the "content" field which has the value which breaks Pomm's escaping. The specific value is:
```
<p>this-breaks-it-)</p>
```

Let me know if you would like any additional info!

**Comment by chanmix51** [comment]
Please close the issue if the fix works with your test case or complete the ticket otherwise.

**Comment by chris-simple** [comment]
Looks good to me, thanks!
