### ISSUE TITLE
Tables without primary keys throw notice on CLI generation

### ISSUE THREAD

**Issue by nspyke** [pomm-project/Foundation#118]
Running the below command
```
$ bin/console pomm:generate:schema-all --psr4 -a CoreBundle db thermal
```
Outputs the following;
```
Scanning schema 'thermal'.
// Below is the output of dump($pk); on line 217 in Inspector.php
array:1 [
  "fields" => null
]

In Inspector.php line 218:
Notice: Trying to access array offset on value of type null  
```

**Comment by artjomsimon** [comment]
@chanmix51 could you cherry-pick this into `master` as well? :+1: :)
We're using `dev-master` via composer and running into this a lot..

**Comment by chanmix51** [comment]
The inspector has been revamped in master, maybe you should be able to use the new inspector. 
I am going to fix the problem on master but I don't understand why no warnings are issued when [tests are launched](https://github.com/pomm-project/Foundation/blob/d9f2acee9544a4104e28de3059be96fcfa9c8c98/sources/tests/Unit/Inspector/LegacyInspector.php#L108).

**Comment by chanmix51** [comment]
done in 3ef281b
