### ISSUE TITLE
Inferring types when values passed as query parameters

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/Foundation#13]
There are no mechanisms today to pass complex types as parameter of prepared or parametrized queries. 

The obvious example would be using a `\DateTime` parameter but this cas is handle in a way which is [more a hack](https://github.com/pomm-project/Foundation/blob/master/sources/lib/QueryParameterExpander.php#L64) than a real way to use complex types.

I suggest to adapt the query system to the following:

```php
    $sql = 'select field from my_table where created_at > $*::timestamp';
    $iterator = $session->getQueryManager()->query($sql, [new \DateTime()]);
```

This does not change the way older queries do work and add extra possibilities:

```php
    $sql = 'select name from station where  position <@ $*::circle';
    $iterator = $session->getQueryManager()->query($sql, [new Circle(…)]);
```
It is still possible to use «normal» notation:

```php
    $sql = 'select name from station where position <@ circle(point($*, $*), $*)';
    $iterator = $session->getQueryManager()->query($sql, […]);
```

This feature implies adding an extra method to the `ConverterInterface` to be able to cast values as short string representation:

```php
    $ts_converter->toPg(new \Datetime, 'timestamp', $session); // returns "timestamp '2015-01-25…'
    $ts_converter->toString(new \DateTime); // returns '2015-01-25…'

    $cl_converter->toPg(new Circle(…), 'circle', $session); // returns 'circle(point(…), …)'
    $cl_converter->toString(new Circle(…)); // returns '<(…), …>'
```

It may not be mandatory to indicate type as parameter since the type is expected on the other side either in the case of parametrized queries or COPY statements.

Any thoughts ?

**Comment by chanmix51** [comment]
Using Postgresql, it is possible to issue the following SQL query:

```sql
prepare pika as select name from station where position <@ $1::circle;
execute pika('<(2, 2), 2>');
```

This means, there is no need to parse the parameters more than what's done already if we follow Postgresql syntax (which I would suggest).

Now, the two last things are:

 1 expand parameters to scalar 
 2 serialize values to their scalar representation

The point 2 is the hotest part of the job. The `ConverterInterface` declares 2 methods for converters:

 * `fromPg()`
 * `toPg()`

`fromPg()` takes a Postgesql scalar output short form values and converts them to a PHP representation. (ie `{1,2,3}` or `'(<(1,2), 3>,"a string")'`.
`toPg()` outputs a Postgresql representation using the « literal decorated format » (ie `int4 '4'`, `timestamp '2015-…'`);

This format is not accepted as query parameter nor COPY command. The converter system needs a new method to convert a PHP representation to Postgresql « standard format ».

Several method names have been proposed on IRC:
 * `toString()`
 * `toPgValue()`
 * `toPgString()`
 * `toExternalText()`
 * `toPgStandardFormat()`

Please feel free to vote for proposed choices or to propose your own.

**Comment by stood** [comment]
toPgStandardFormat() :+1:

**Comment by tlode** [comment]
toPgStandardFormat()

**Comment by lbol** [comment]
toPgStandardFormat()

**Comment by chanmix51** [comment]
Ok, let's go for «toPgStandardFormat».

**Comment by chanmix51** [comment]
Code now lies in the [converters branch](https://github.com/pomm-project/Foundation/tree/converters).

It is possible to perform queries like

    use \PommProject\Foundation\Converter\Type;

    $circle = new Circle(…);

    $stations = $session
        ->getQueryManager()
        ->query(
            "select * from station where position <@ $*::circle",
            [ $circle ]
            );

It also works with array parameters and timestamps:

    ->query(
        "select * from my_table where created_at > $*::timestamptz and my_field = ANY($*::int4[])"
        [new \DateTime(…), [1,2,3]]
        );

This feature will be kept in the `converters` branch for tests. Please provide feedbacks.

**Comment by chanmix51** [comment]
Done in 01560e8
