### ISSUE TITLE
Move FoundationSessionAtoum and VanillaSessionAtoum classes in sources/test

### ISSUE THREAD

**Issue by sanpii** [pomm-project/Foundation#16]
These classes are used for unit testing, they shouldn’t be expose as pomm public API. This introduces a dependency to Atoum.

* [FoundationSessionAtoum](https://github.com/pomm-project/Foundation/blob/master/sources/lib/Tester/FoundationSessionAtoum.php)
* [VanillaSessionAtoum](https://github.com/pomm-project/Foundation/blob/master/sources/lib/Tester/VanillaSessionAtoum.php)

**Comment by stood** [comment]
:+1:

**Comment by stood** [comment]
no comments ? it's ok ?

**Comment by sanpii** [comment]
`autoload-dev` is a root only directive :disappointed:

**Comment by chanmix51** [comment]
You did fight bravely :beer:
