### ISSUE TITLE
Use of own types with schema

### ISSUE THREAD

**Issue by rijad-cz** [pomm-project/Foundation#21]
Hello, 

I have found and another problem. I will use my own types and I will to have they in another schema than "public" that is supported by postgres, but in pomm is a little bug. 

There is a following regular expression In the method "getParametersType"  of trait "PommProject\Foundation\QueryManager\QueryParameterParserTrait".

```php
preg_match_all('/\$\*(?:::([\w]+(?:\[\])?))?/', $string, $matchs);
```

But it will not match to type with schema. The correct one should looks like 

```php
preg_match_all('/\$\*(?:::([\w]+(?:\[\])?(\.[\w]+)?))?/', $string, $matchs);
```

It is related with my previous issue https://github.com/pomm-project/Foundation/issues/20, because when you will use my type definitions, you will get an error.

**Comment by chanmix51** [comment]
Normally, this is the case since [this commit](https://github.com/pomm-project/Foundation/commit/1bb46cb02f70a5be9c4926fc2c1380ce629f8b41#diff-a86fc3445bc15ece26377ccf0ed5a3e4L71). Maybe your vendors are not up to date.

Could you please update your vendors and confirm this is ok ?

**Comment by rijad-cz** [comment]
You are right. It works with the newest version. Also sorry for reporting. I found this bug on Friday and I didn't update vendors yesterday. Thank you

**Comment by chanmix51** [comment]
Can we close this issue ?

**Comment by rijad-cz** [comment]
Yes
