### ISSUE TITLE
Add a closeAll() method to Pomm service

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/Foundation#27]
For now, the only place closing all the connections is needed is the PommBundle. It would be nice to add this capability in the Pomm service.

**Comment by sanpii** [comment]
:+1: 

I would be happy to remove the `foreach` from `PommBundle::shutdown()`!

**Comment by chanmix51** [comment]
Done in a6d5e15fc2d21153375c6c983d8b5bfe40916c0a
