### ISSUE TITLE
Pomm2 requires PostgreSQL 9.1+

### ISSUE THREAD

**Issue by rdavaillaud** [pomm-project/Foundation#35]
Not a really big issue here, 
because of the following line n the Inspector::getTableFieldInformation() function, 
https://github.com/pomm-project/Foundation/blob/74ac09ce71a7e2c21346239084de61c42ff31016/sources/lib/Inspector/Inspector.php#L127

I can't generate relation on my Pg 9.0 database.

=> the "format()" operator is available since Pg 9.1

**Comment by chanmix51** [comment]
You will have other issues with Pg 9.0 since it is not supported by Pomm2 hence it has not been tested with it. Can you contact me by mail ?

**Comment by chanmix51** [comment]
It is now displayed on the README, can we close it ?

**Comment by rdavaillaud** [comment]
let me think.. well, yes ;)

**Comment by chanmix51** [comment]
Easy one ;)
