### ISSUE TITLE
Provide a way to create Where NOT IN 

### ISSUE THREAD

**Issue by v3106** [pomm-project/Foundation#36]
May be like this, `Where::createWhereIn($element, $values, $inverse = true)`? Changes would be minimal.

**Comment by sanpii** [comment]
> like this, Where::createWhereIn($element, $values, $inverse = true)

Flag argument is not a good idea.

**Comment by v3106** [comment]
Agreed, I'm just tried to illustrate the issue.

**Comment by chanmix51** [comment]
The actuel implementation is … well … crap because it adds the `IN` SQL keyword. In the actual form, it would be better to create a `createWhereNotIn` method afais.

**Comment by chanmix51** [comment]
Fix in 9acffd6
