### ISSUE TITLE
ConnectionConfigurator's .ctor param

### ISSUE THREAD

**Issue by ronanguilloux** [pomm-project/Foundation#44]
see https://scrutinizer-ci.com/g/pomm-project/Foundation/inspections/197452e1-2da4-4a8a-8903-c0496f0f9445/issues/files/sources/lib/Session/ConnectionConfigurator.php?status=existing&orderField=path&order=asc#inspectioncomment-847558763

**Comment by chanmix51** [comment]
Isn't it ok since your PR ?

**Comment by ronanguilloux** [comment]
Yop! https://github.com/ronanguilloux/Foundation/commit/70d1699341d8fc1afe542a6f1eb9001301438350#commitcomment-11361192
