### ISSUE TITLE
FlexibleEntity serialization

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/Foundation#5]
Tobias Lode wrote:
I started implementing a Pomm 2 bundle based on your repo, already merged in the security layer and user provider of Pomm 1. Now I've got somehow stuck on the JMSSerializer lib, trying to test a rest api with FOSRestBundle and Pomm. I would like to use the exclude/expose annotations on my users entity, but cannot solve the problem, since the properties are held in the fields map. I also tried to exclude/expose by configuration file, but that also didn’t have an effect.
I am curious if you already have a solution on how to accomplish serialization of Pomm 2 entities.

**Comment by chanmix51** [comment]
Can we close this issue ?

**Comment by chanmix51** [comment]
Can we close this issue ?

**Comment by tlode** [comment]
yes, thanks
