### ISSUE TITLE
Consider fixing PSR code style issues

### ISSUE THREAD

**Issue by v3106** [pomm-project/Foundation#54]
```
>phpcs --standard=psr2 --report=summary sources
...
----------------------------------------------------------------------
A TOTAL OF 165 ERRORS AND 28 WARNINGS WERE FOUND IN 39 FILES
----------------------------------------------------------------------
PHPCBF CAN FIX 164 OF THESE SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

It would be great to have these issues fixed in all pomm projects. There are automated tools for that, like phpcbf, php-cs-fixer. What do you think of this?

**Comment by sanpii** [comment]
:+1:

**Comment by ronanguilloux** [comment]
php-cs-fix to the rescue ;-)

**Comment by chanmix51** [comment]
Yes, phpcs also adds sf conventions over psr2, we need to correctly configure it to follow Pomm CS  instead.

**Comment by chanmix51** [comment]
I think @v3106 did the job well, can we close this issue ?

**Comment by v3106** [comment]
I don't think I fixed all the issues and I don't know exactly what should be fixed, because you saying that `phpcs --standard=psr2` is redundant here. I think we should have approved ruleset for pomm projects. This can be a start:
```xml
<?xml version="1.0"?>
<ruleset name="Pomm">
    <file>sources</file>
    <rule ref="PSR2">
        <exclude name="PSR2.Methods.FunctionCallSignature.ContentAfterOpenBracket"/>
    </rule>
</ruleset>
```
You should run phpcs like this `phpcs --standard=PSR2 sources -s` and add non-errors to the exclude list.

**Comment by sanpii** [comment]
I fixed most of violations in PR #79 but some seems difficult to fix smartly:
```
FILE: sources/lib/Session/Connection.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
  57 | WARNING | Line exceeds 120 characters; contains 143 characters
----------------------------------------------------------------------


FILE: sources/tests/Fixture/InspectorFixture.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
 44 | WARNING | Line exceeds 120 characters; contains 160 characters
 45 | WARNING | Line exceeds 120 characters; contains 192 characters
----------------------------------------------------------------------


FILE: sources/tests/Unit/Converter/PgArray.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 106 | WARNING | Line exceeds 120 characters; contains 133 characters
----------------------------------------------------------------------


FILE: sources/tests/Unit/QueryManager/SimpleQueryManager.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 63 | WARNING | Line exceeds 120 characters; contains 162 characters
----------------------------------------------------------------------

Time: 1.85 secs; Memory: 16Mb
```
[sources/lib/Session/Connection.php#L57](https://github.com/sanpii/Foundation/blob/code-style/sources/lib/Session/Connection.php#L57)
[sources/tests/Fixture/InspectorFixture.php#L44](https://github.com/sanpii/Foundation/blob/code-style/sources/tests/Fixture/InspectorFixture.php#L44)
[sources/tests/Fixture/InspectorFixture.php#L45](https://github.com/sanpii/Foundation/blob/code-style/sources/tests/Fixture/InspectorFixture.php#L45)
[sources/tests/Unit/Converter/PgArray.php#L106](https://github.com/sanpii/Foundation/blob/code-style/sources/tests/Unit/Converter/PgArray.php#L106)
[sources/tests/Unit/QueryManager/SimpleQueryManager.php#L63](https://github.com/sanpii/Foundation/blob/code-style/sources/tests/Unit/QueryManager/SimpleQueryManager.php#L63)

**Comment by chanmix51** [comment]
Do unit tests have to be that smart ?

**Comment by sanpii** [comment]
@chanmix51 Yes, I included `phpcs` in travis build.

**Comment by sanpii** [comment]
https://travis-ci.org/pomm-project/Foundation/jobs/176378190#L170

**Comment by chanmix51** [comment]
Thank you @sanpii :+1:
