### ISSUE TITLE
Support for DateTimeImmutable

### ISSUE THREAD

**Issue by tlode** [pomm-project/Foundation#68]
Will there be support for `DateTimeImmutable` objects in the future?

Currently,  [Converter\PgTimestamp](https://github.com/pomm-project/Foundation/blob/master/sources/lib/Converter/PgTimestamp.php) converts only from `DateTime` instances (or string representations) and to `DateTime` instances. Using `DateTimeImmutable` won't work.

Unfortunately since `DateTimeInterface` is introduced in PHP 5.5, changing this would break compatibility with PHP 5.4.

Are there any plans to drop PHP 5.4 support in pomm and use `DateTimeImmutable` instead of `DateTime`?

**Comment by chanmix51** [comment]
It could be injected as parameter in the converter’s constructor ?

**Comment by tlode** [comment]
This sounds good. What do you mean by "it"? The class name?

**Comment by chanmix51** [comment]
Yes, the class name. Note that is must take a string representing a ` 'Y-m-d H:i:s.uP'` date in the constructor. Otherwise, you can override the timestamp converter by an `ImmutableTimestampConverter` in your `SessionBuilder`.

**Comment by tlode** [comment]
Thank you. It's great, pomm is so easy to extend.
