### ISSUE TITLE
no converters associated to the regconfig type

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/Foundation#76]
The regconfig type can be useful to pass dictionary as parameter to full text search queries. Even though not precising the type of the parameter seems to work, it would be good to enforce the parameter type.

**Comment by sanpii** [comment]
Something like that https://github.com/sanpii/Foundation/commit/3f351e8ac1d92f42c4970d51d1a1a42fac65f1f9 ?

**Comment by chanmix51** [comment]
Sorry, my bad, it was fixed by 68e777b0
