### ISSUE TITLE
No converter registered for type 'public.citext'

### ISSUE THREAD

**Issue by lunika** [pomm-project/Foundation#84]
Hello,

I use the extension [citext](https://www.postgresql.org/docs/current/static/citext.html) which is not recognized by default in POMM. I have my own sessionBuilder so I had it to don't have an error anymore.

Do you think this type can be added in the foundation `SessionBuilder` ? Do you consider that type added by a postgresql extension should not be present in the foundation `SessionBuilder` ?

This is what I made in my `SessionBuilder` : 

```php
protected function initializeConverterHolder(ConverterHolder $converter_holder)
{
    parent::initializeConverterHolder($converter_holder);
    $converter_holder->addTypeToConverter('String', 'public.citext');
    $converter_holder->addTypeToConverter('String', 'citext');
}
```

**Comment by chanmix51** [comment]
Good catch 👍

**Comment by lunika** [comment]
@chanmix51 I can create the PR to add this type if you want.

**Comment by chanmix51** [comment]
\o/ with pleasure (on master).

**Comment by artjomsimon** [comment]
I've followed [this StackOverflow advice to move all extensions into their own schema](https://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas) and now the expected extension isn't known in `public.citext` but in `extensions.citext` in my app, so I had to override the `initializeConverterHolder()` like @lunika mentioned.

@chanmix51 is there a way to tell the SessionBuilder to convert `citext` (and probably other extension's types) not based on any schema they were created in? Do you think it's a good idea at all?

**Comment by chanmix51** [comment]
In Postgres, you can define several types named `citext` if they are in different schemas. My advice would be to put every shared functions / types etc. in the public schema so they are in the search path by default. If you feel better with creating a `shared` or `utils` or `extensions` schema then you need to either change the search path of the connection, or define converters for those types prefixed with their schema.
