### ISSUE TITLE
impossible to retrieve json when using an array_agg

### ISSUE THREAD

**Issue by lunika** [pomm-project/Foundation#87]
Hi,

In a query I use the `array_agg` to aggregate a collection of entries, doing that I can retrieve my pomm entites in my php code. The problem is that in this aggregation I have json column and the json has several `\` added and produces something like this : `""{\\"price\\":900,\\"foo\\":1,\\"bar\\":\\"month\\"}""` and the `PgJson` return null because json_decode returns `null` and no error are checked.

First of all I think that testing if the returned value of `json_decode` is equal to `false` is wrong because the documentation says `NULL is returned if the json cannot be decoded or if the encoded data is deeper than the recursion limit.`. You should test the `json_last_error` which contains the state of the last json_decode (also if there is no error) :
```php
if (JSON_ERROR_NONE !== json_last_error()) {
  throw new ConverterException(...
}
```

And for my initial problem I fixed it with a regex but I have no idea if it's a good idea to do that way :

```php
    public function fromPg($data, $type, Session $session)
    {
        if (trim($data) === '') {
            return null;
        }

        if (1 === preg_match('@\\\\\\\\":@', $data)) {
            $data = stripslashes($data);
        }

        $return = json_decode($data, $this->is_array);

        if ($return === false) {
            throw new ConverterException(
                sprintf(
                    "Could not convert Json to PHP %s, driver said '%s'.\n%s",
                    $this->is_array ? 'array' : 'object',
                    json_last_error(),
                    $data
                )
            );
        }

        return $return;
    }
```

Do you have a better idea how to fix the issue ?

Thanks

**Comment by chanmix51** [comment]
Ok, I’ll sum up [this thread of Stack-Overflow](http://stackoverflow.com/questions/42347304/distinct-empty-strings-from-nulls-in-a-csv-input) here about this bug.

There is a mind gap between PHP and Postgres community. To handle polymorphism properly, Pg does type NULL (no defined value) so `NULL::text` or `NULL::int4` do mean _no defined value for this type_. For PHP, NULL is not of a type because it is undefined. As the CSV files return strings, theses pieces of string cannot be null because they are typed hence `("a","",,"b")` means `['a', '', '', 'b']`. 

This behavior complies with the [RFC4180](https://www.ietf.org/rfc/rfc4180.txt). Even though this RFC is only informational and has been drew to make the mime-type `text/csv` compatible with Ms/Excel, it is the model for how PHP parses CSV lines. 

There is (almost) no hope to patch [the code](https://github.com/php/php-src/blob/master/ext/standard/file.c#L2084) of the underlying C function. 

Choices are now:
 * either to code a state machine to parse CSV in PHP with the performance issues and bugs one can expect
 * or to let this bug as is and document it
 * or to remove this functionality with its bug from Pomm

Any thoughts ?

**Comment by lunika** [comment]
I'm sorry but I don't see the relation between your answer and my issue. I have no problem with CSV, nor `null` value

**Comment by lunika** [comment]
The first part of this issue (check if there is an error or not on a json decoded value) was fixed in this PR https://github.com/pomm-project/Foundation/pull/86

**Comment by chanmix51** [comment]
true … wrong bug … need a :truck:  of :coffee: this morning :sleepy:

**Comment by chanmix51** [comment]
I have done a little check this evening, I added a test containing an array of `jsonb` which could be an array aggregation on `jsonb` field.

```sql
select ARRAY['{"pika": "chu"}'::jsonb, '{"something": ["with", "love"]}'::jsonb, '{"nesting": {"nested": "deep"}}']::jsonb[];
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                  array                                                  │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ {"{\"pika\": \"chu\"}","{\"something\": [\"with\", \"love\"]}","{\"nesting\": {\"nested\": \"deep\"}}"} │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)
```

So I added the following test in the `PgArray` converter which I suspected not to escape slashes correctly but:

```php
->array($converter->fromPg('{"{\"pika\": \"chu\"}","{\"something\": [\"with\", \"love\"]}","{\"nesting\": {\"nested\": \"deep\"}}"}', 'jsonb', $session))
->isEqualTo([['pika' => 'chu'], ['something' => ['with', 'love']], ['nesting' => ['nested' => 'deep']]])
```

is OK, so the string is slash stripped correctly and both converters behaved correctly. Can you provide a failing case?

**Comment by lunika** [comment]
the raw result postgresql returned is this and it's the result of my array aggreg
```
{"(1fa596ea-2e90-4f9b-a497-d1b382fb0d2a,4370b9a5-d25a-4b41-9ca5-27fb00988b21,\"\"\"{\\\\\"\"price
\\\\\"\":900,\\\\\"\"foo\\\\\"\":1,\\\\\"\"bar\\\\\"\":\\\\\"\"baz\\\\\"\"}\"\"\",\"2017-03-20 13:49:58.684
616\",foo)"}
```

**Comment by lunika** [comment]
Hmmm my json inserted in database looks like weird, this is maybe the reason I have all of this backslahes :
`"{\"price\":900,\"foo\":1,\"bar\":\"baz\"}"` so the issue is maybe when the data is inserted, not when readed.

**Comment by chanmix51** [comment]
Mmmh it looks like you are passing a Json string as argument to a Json field instead of using an array (one of PHP representations of JSON). Can you tell if the value stored in the Entity is a string or an array?

**Comment by lunika** [comment]
it's a string, the result of a `json_encode` : 
```
$this->set('attributes', json_encode(['foo' => 'bar']));
```

**Comment by lunika** [comment]
ok so if I understand, pomm is able to do this for me. I tested by passing an array and I have no more problem...

**Comment by lunika** [comment]
I close this issue, it was a pebkac issue :-)
