### ISSUE TITLE
Crash when PHP’s timezone is not set

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/Foundation#90]
When a connection is opened, an error is thrown if the timezone is not set in the `PHP.ini` file. This prerequisite must be properly handled.

**Comment by pounard** [comment]
This is a common error with many libraries and frameworks, my advice would be that you must not handle this case, if it's just a warning, let PHP warn, it reveals a misconfigured environment that MUST be configured.

**Comment by pounard** [comment]
You can always do something like:

```php
if (!@date_default_timezone_get()) {
    date_default_timezone_set('Europe/Paris');
}
```

If you really wishes to avoid this error, but I still would let the user know there is a configuration problem, it's even more important since the timezone might affect how dates will be processed between PHP and PgSQL, it MUST be configured properly.

**Comment by chanmix51** [comment]
Here is the [answer](http://stackoverflow.com/a/3595188/1222135), use `date_default_timezone_get()` instead of `ini_get()`.
