### ISSUE TITLE
Pomm and Symfony existing project

### ISSUE THREAD

**Issue by methodeprog** [pomm-project/Foundation#99]
Hi Gregoire,

I ve a Advanced Symfony Project with doctrine and Mysql,
I ve tried Pomm quick set up and could not connect my database with ".pomm_cli_bootstrap.php".
.pomm_cli_bootstrap.php is in the main symfony project.
Issue : 
Could not load configuration '.pomm_cli_bootstrap.php'

**Comment by chanmix51** [comment]
Hi Methodprog.

This is the ticket system to report bugs on Pomm’s Foundation project. If you want to find help ask on [stackoverflow](https://stackoverflow.com/questions/tagged/pomm) using at least the tag pomm.

Thank you.
